.TH GRAVIUM-CLI "1" "June 2016" "gravium-cli 0.12"
.SH NAME
gravium-cli \- a remote procedure call client for Gravium Core. 
.SH SYNOPSIS
gravium-cli [options] <command> [params] \- Send command to Gravium Core. 
.TP
gravium-cli [options] help \- Asks Gravium Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the gravium-cli program. gravium-cli is an RPC client used to send commands to Gravium Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBgraviumd\fP, \fBgravium.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
